databaseChangeLog:
  - changeSet:
      id: create-table-articles
      author: IRZaripov
      changes:
        - createTable:
            tableName: article_bodies
            remarks: "Таблица статей"
            columns:
              - column:
                  name: id
                  type: BINARY(16)
                  remarks: "Уникальный идентификатор статьи"
                  constraints:
                    nullable: false
                    primaryKey: true
                    unique: true
              - column:
                  name: title
                  type: VARCHAR(255)
                  remarks: "Заголовок статьи"
              - column:
                  name: author
                  type: VARCHAR(255)
                  remarks: "Логин автора статьи"
                  constraints:
                    foreignKeyName: fk_username_user_credentials
                    references: user_credentials(username)
              - column:
                  name: text
                  type: text
                  remarks: "Текст статьи"
              - column:
                  name: created_ts
                  type: datetime
                  remarks: "Время создания статьи"
  - changeSet:
      id: create-table-articles-add-null-constraints
      author: IRZaripov
      changes:
        - addNotNullConstraint:  
            columnName: title 
            columnDataType: VARCHAR(255)  
            tableName: article_bodies  
        - addNotNullConstraint:  
            columnName: author
            columnDataType: VARCHAR(255)  
            tableName: article_bodies
        - addNotNullConstraint:  
            columnName: created_ts   
            columnDataType: datetime   
            tableName: article_bodies
  - changeSet:
      id: create-table-articles-add-default-values
      author: IRZaripov
      changes:
        - addDefaultValue:
            columnDataType: datetime  
            columnName: created_ts   
            defaultValueDate: (now())
            tableName: article_bodies
  - changeSet:
      id: create-table-articles-generate-id
      author: IRZaripov
      changes:
        - sql:
            dbms: mysql
            splitStatements: false
            endDelimiter: \nGO
            sql:  CREATE TRIGGER blog.article_bodies_id_defaultValue
                  BEFORE INSERT ON article_bodies
                  FOR EACH ROW
                  BEGIN
                  IF (NEW.id IS NULL) THEN
                  SET NEW.id = UUID_TO_BIN(UUID());
                  END IF;
                  END;
  - changeSet:
      id: create-table-articles-last-uuid
      author: IRZaripov
      changes:
        - sql:
            dbms: mysql
            splitStatements: false
            endDelimiter: \nGO
            sql:  CREATE TRIGGER blog.article_bodies_last_id
                  AFTER INSERT ON article_bodies
                  FOR EACH ROW
                  SET @last_article_id = NEW.id;